name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: securedeveloper
          template: classic
          config_timezone: Europe/Vienna

          filename: github-metrics.svg
          output_action: commit
          committer_message: "chore: update metrics"

          base: header,activity,community,repositories,metadata
          base_indepth: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_details: percentage
          plugin_languages_indepth: yes

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit,pull_request,issue

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_stars: yes
          plugin_stars_limit: 6

          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_topics_mode: icons

